version: '3.8'

services:
    main:
        container_name: nestjs_api
        image: nestjs-api:1.0.0
        env_file:
            - .dev.env
        build: .
        command: npm run start:dev
        ports:
            - 5000:5000
            - 9229:9229
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: always
        depends_on:
            couchdb:
                condition: service_started
    couchdb:
        container_name: couchdb
        image: couchdb:3.2
        env_file:
            - .dev.env
        restart: always
        ports:
            - 5984:5984
        volumes:
            - ./dbdata:/opt/couchdb/data
    initializer:
        image: curlimages/curl
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            main:
                condition: service_started
        command: [
            "sh",
            "-c",
            "sleep 15 && 
            curl -u admin:adminpass -X PUT couchdb:5984/_users && 
            curl -u admin:adminpass -X PUT couchdb:5984/_replicator && 
            curl -u admin:adminpass -X PUT couchdb:5984/_global_changes &&
            curl -H 'Content-Type: application/json'  
                -u admin:adminpass 
                -X POST couchdb:5984/authors/_index 
                -d '{\"index\": {\"fields\": [\"_id\"] },\"name\": \"id-json-index\",\"type\": \"json\"}' && 
            curl -H 'Content-Type: application/json'  
                -u admin:adminpass 
                -X POST couchdb:5984/books/_index 
                -d '{\"index\": {\"fields\": [\"_id\"] },\"name\": \"id-json-index\",\"type\": \"json\"}'"
        ]
volumes:
    couchdb-data: