version: '2.2'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .prod.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229 
    depends_on:
      - couchdb
    restart: always

  couchdb:
    container_name: couchdb
    image: couchdb:2
    env_file:
      - .dev.env 
    restart: always
    ports:
      - "5984:5984"
    volumes:
        - ./dbdata:/opt/couchdb/data

  initializer:
    image: curlimages/curl
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - couchdb
    command: ["sh","-c","sleep 15 && curl -u admin:adminpass -X PUT couchdb:5984/_users && curl -u admin:adminpass -X PUT couchdb:5984/_replicator && curl -u admin:adminpass -X PUT couchdb:5984/_global_changes"]
volumes:
  couchdb-data: